apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  people-who-view-secrets
subjects:
- kind: User
  name: https://35.224.110.0:8443/realms/testing#sub
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: https://35.224.110.0:8443/realms/testing#e7219b73-c186-4576-bf7e-e86fac565eb8
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secret-viewer
  apiGroup: rbac.authorization.k8s.io